version: '#{build}'
image: 'Visual Studio 2017'
branches:
  only:
  - master
skip_tags: true
clone_depth: 1
build_script:
  - mkdir build
  - cd build
  - cmake -G "Visual Studio 15 Win64" -DCMAKE_CONFIGURATION_TYPES="Release" -DCMAKE_PREFIX_PATH=C:\Qt\5.13.0\msvc2017_64 ..
  - cmake --build . --config Release
artifacts:
- path: build/build/Release/RcloneBrowser.exe
test: off
deploy: off
