git:
  depth: 1

matrix:
  include:

    - os: linux
      language: cpp
      sudo: false
      dist: bionic
      addons:
        apt:
          packages:
            - qttools5-dev
            - qtmultimedia5-dev

      script:
        - mkdir build && cd build
        - cmake ..
        - cmake --build .

    - os: osx
      language: cpp
      install:
        - brew update
        - brew install qt5
      script:
        - mkdir build && cd build
        - cmake -DCMAKE_PREFIX_PATH=/usr/local/opt/qt5/lib/cmake ..
        - cmake --build .
